// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4MY5tQw40YAHBYwn_4Nnv2OxZjNNptqk',
    appId: '1:33869572673:web:77e1f07ab8831c78b9b4c0',
    messagingSenderId: '33869572673',
    projectId: 'health-app-b51cf',
    authDomain: 'health-app-b51cf.firebaseapp.com',
    storageBucket: 'health-app-b51cf.firebasestorage.app',
    measurementId: 'G-07DPRGTJ78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjVRZrJX9w7DNIrnOdxoEPP4ZlbzWRxrg',
    appId: '1:33869572673:android:f5acfb589ee9268ab9b4c0',
    messagingSenderId: '33869572673',
    projectId: 'health-app-b51cf',
    storageBucket: 'health-app-b51cf.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4MY5tQw40YAHBYwn_4Nnv2OxZjNNptqk',
    appId: '1:33869572673:web:d1c8210464f4b47fb9b4c0',
    messagingSenderId: '33869572673',
    projectId: 'health-app-b51cf',
    authDomain: 'health-app-b51cf.firebaseapp.com',
    storageBucket: 'health-app-b51cf.firebasestorage.app',
    measurementId: 'G-BQ10SG9RL0',
  );
}
